"""added saved decks

Revision ID: ff1c6b7832a5
Revises: 4aafad94a89a
Create Date: 2021-12-08 12:48:31.373140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1c6b7832a5'
down_revision = '4aafad94a89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.Column('deck_name', sa.String(length=150), nullable=True),
    sa.Column('card_1', sa.Integer(), nullable=True),
    sa.Column('card_2', sa.Integer(), nullable=True),
    sa.Column('card_3', sa.Integer(), nullable=True),
    sa.Column('card_4', sa.Integer(), nullable=True),
    sa.Column('card_5', sa.Integer(), nullable=True),
    sa.Column('card_6', sa.Integer(), nullable=True),
    sa.Column('card_7', sa.Integer(), nullable=True),
    sa.Column('card_8', sa.Integer(), nullable=True),
    sa.Column('card_9', sa.Integer(), nullable=True),
    sa.Column('card_10', sa.Integer(), nullable=True),
    sa.Column('card_11', sa.Integer(), nullable=True),
    sa.Column('card_12', sa.Integer(), nullable=True),
    sa.Column('card_13', sa.Integer(), nullable=True),
    sa.Column('card_14', sa.Integer(), nullable=True),
    sa.Column('card_15', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck')
    # ### end Alembic commands ###
